import {
    lev,
    barbos,
    sirius,
    purina,
    pethelp,
    happypaw,
    lico,
    josera,
    whiskas,
  } from '../../images';
  import { nanoid } from '@reduxjs/toolkit';
  
  export const FriendsData = [
    {
      id: nanoid(4),
      name: 'ЛКП "ЛЕВ"',
      time: '8:00 - 19:00',
      address: 'Promuslova Street, 56',
      email: 'lkplev@gmail.com',
      phone: '+380 32 293 30 41',
      image: lev,
      link: 'https://www.lkplev.com',
    },
    {
      id: nanoid(4),
      name: 'Барбос',
      time: '8:00 - 20:00',
      address: 'Grigorenka Street, 56',
      email: 'barbos@gmail.com',
      phone: '+380 66 488 0480',
      image: barbos,
      link: 'https://www.facebook.com/NGO.Barbos',
    },
    {
      id: nanoid(4),
      name: 'Whiskas',
      time: 'day and night',
      address: 'website only',
      email: 'whiskas@gmail.com',
      phone: '0 800 500 155',
      image: whiskas,
      link: 'http://www.whiskas.ua',
    },
    {
      id: nanoid(4),
      name: 'Happy Paw',
      time: '9:00 - 19:00',
      address: 'Chota Rystaveli Street, 44',
      email: 'hello@happypaw.ua',
      phone: '+380 44 290 03 29',
      image: happypaw,
      link: 'http://www.happypaw.ua/ua/',
    },
    {
      id: nanoid(4),
      name: 'PetHelp',
      time: 'day and night',
      address: 'website only',
      email: 'pithelp.ukr@gmail.com',
      phone: 'email only',
      image: pethelp,
      link: 'http://www.pethelp.com.ua',
    },
    {
      id: nanoid(4),
      name: 'Сіріус',
      time: '11:00 - 16:00',
      address: 'Fedorivka, Kyiv Oblast',
      email: 'dogcat.sirius@gmail.com',
      phone: '+380 93 193 40 69',
      image: sirius,
      link: 'http://www.dogcat.com.ua',
    },
    {
      id: nanoid(4),
      name: 'PURINA',
      time: 'day and night',
      address: 'website only',
      email: 'info@ua.nestle.com',
      phone: '+1 800 778 7462',
      image: purina,
      link: 'http://www.purina.ua',
    },
    {
      id: nanoid(4),
      name: 'Josera',
      time: '9:00 - 17:00',
      address: 'Sholom-Aleikhema St, 11',
      email: 'info@josera.ua',
      phone: '0 800 409 060',
      image: josera,
      link: 'http://www.josera.ua',
    },
    {
      id: nanoid(4),
      name: 'LICO',
      time: '9:00 - 20:00',
      address: 'Dryhetiv Street, 77',
      email: 'lico@gmail.com',
      phone: '+380 97 509 80 05',
      image: lico,
      link: 'http://www.lico.vet',
    },
  ];