export { default as lev } from './Friends/lev.png';
export { default as barbos } from './Friends/barbos.png';
export { default as happypaw } from './Friends/happypaw.png';
export { default as josera } from './Friends/josera.png';
export { default as whiskas } from './Friends/whiskas.png';
export { default as sirius } from './Friends/sirius.png';
export { default as purina } from './Friends/purina.png';
export { default as pethelp } from './Friends/pethelp.png';
export { default as lico } from './Friends/lico.png';
